### ISSUE TITLE
allNotificationList() is not working

### ISSUE THREAD

**Issue by iaditya** [cakemanager/cakephp-notifier#10]
Here is my code - 
`dump($this->Notifier->allNotificationList($userid, true));`

got Error : 

> Error: Call to undefined method Notifier\Controller\Component\NotifierComponent::allNotificationList() 
> File /Users/adityagupta/talkadoc/vendor/cakedc/users/src/Controller/UsersController.php 
> Line: 70

**Comment by bobmulder** [comment]
The docs are wrong, you should use `getNotifications`. Sorry for being not clear enough!

PS. You should use `debug()` instead of `dump()` ;)

**Comment by iaditya** [comment]
So how do we get to read/unread notifications?

**Comment by bobmulder** [comment]
See here: https://github.com/cakemanager/cakephp-notifier/blob/master/src/Controller/Component/NotifierComponent.php#L96

Second parameter is used for the state (`true`, or `false`)

**Comment by iaditya** [comment]
Ya . it's ok 
But , when we create a notification, it  stores the state's value 1 not 0. 

Thanks

**Comment by bobmulder** [comment]
That means it isn't read yet...

**Comment by iaditya** [comment]
It adds a new notification but the state value is 1.
and for unread notification - 
`$this->Notifier->countNotifications($userid, false);`
got value 0;
and 
`$this->Notifier->countNotifications($userid, true);` // it's working
got value - (number of notifications)

**Comment by iaditya** [comment]
Hey , Please tell me on thing ,
state value  = 1 means true ?

And what is the logic behind changing the value of state in notifications, so we get to read/unread notifications?
How does value changed?

**Comment by bobmulder** [comment]
Value will automatically change when retrieving the notification...

**Comment by bobmulder** [comment]
https://github.com/cakemanager/cakephp-cakeadmin/blob/master/src/Controller/Admin/NotificationsController.php#L37

**Comment by iaditya** [comment]
Once again
thank you.
