### ISSUE TITLE
NotificationsController could not be found.

### ISSUE THREAD

**Issue by mandeepkumar0856** [cakemanager/cakephp-notifier#11]
when i install that composer package according the docs rule and then i run it on localhost as localhost/mann/notifications     then it gives me error here could not found NotificationsController.
?which type of that issue.please help me

**Comment by iaditya** [comment]
In controller you have to add namespace - `use Notifier\Utility\NotificationManager;`
And you have to load the component in controller initialize() method - `$this->loadComponent('Notifier.Notifier');`

**Comment by mandeepkumar0856** [comment]
hello dears iaditya i make a controller here like as if any mistake or wrong controller then please tell me
<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Event\Event;

use Notifier\Utility\NotificationManager;
class NotificationsController extends AppController
{
    public function initialize()
    {
        parent::initialize();
        $this->loadComponent('Notifier.Notifier');
    }
}
?>

**Comment by iaditya** [comment]
so tell me where did you define templates ?

**Comment by iaditya** [comment]
In bootstrap file - 

```
Plugin::load('Notifier', ['bootstrap' => true, 'routes' => true, 'autoload' => true]);
$notificationManager = new \Notifier\Utility\NotificationManager();
$notificationManager->addTemplate('newT', [
    'title' => ':name',
    'body' => ':username',
]);
```

**Comment by mandeepkumar0856** [comment]
i don't change the template that are on same location like as vendor/cakemanager/cakephp-notifier/src/Utility/NotificationManager.php
or may i need to add ant template ?if yes then where i  add them?

**Comment by iaditya** [comment]
In bootstrap.php , you have to add template 
And In controller's method - 
`$notificationManager = new notificationManager();`
`$data;`

```
$notificationManager->addRecipientList('recL', [$id]);
              $this->Notifier->notify([
                'recipientLists' => 'recL',
                'template' => 'newT', // you defined in bootstrap.php 
                'vars' => [
                  'username' => $data->username,
                  'name' => $data->first_name,
                ],
              ]);
```

**Comment by iaditya** [comment]
And For viewing notifications , you can add a method but load component and namespace also. ok
notifications($id) {
$notifications = $this->Notifier->getNotifications();
$this->set('notifications', $notifications);
}

**Comment by mandeepkumar0856** [comment]
in bootstrap.php file i add the above line for template that's told by you
 Plugin::load('Notifier', ['bootstrap' => true, 'routes' => true, 'autoload' => true]);
$notificationManager = new \Notifier\Utility\NotificationManager();
$notificationManager->addTemplate('newT', [
    'title' => ':name',
    'body' => ':username',
]);
And in a controller i  push  the above line  which are sent by you like as
use Notifier\Utility\NotificationManager;
class NotificationsController extends AppController
{
$notificationManager = new notificationManager();
$data;

$notificationManager->addRecipientList('recL', [$id]);
$this->Notifier->notify([
'recipientLists' => 'recL',
'template' => 'newT', // you defined in bootstrap.php
'vars' => [
'username' => $data->username,
'name' => $data->first_name,
],
]);
    public function initialize()
    {
        parent::initialize();
        $this->loadComponent('Notifier.Notifier');
    }
}
i have one confusion here   that class
class NotificationsController extends AppController 
may i need to chane here as
class NotificationsController extends NotifierComponent
or no need to do this?so please tell me my controller is wrong or right or may i need to some changes here...

**Comment by iaditya** [comment]
I think you first read the documentation.
