### ISSUE TITLE
Fix release description for 1.0

### ISSUE THREAD

**Issue by dakota** [cakemanager/cakephp-notifier#12]
The description for the release of 1.0 (https://github.com/cakemanager/cakephp-notifier/releases/tag/1.0.0) mentions

> The CakePHP core team is happy to announce...

Please remove this, since the CakePHP core team has nothing to do with this plugin! :) Also, maybe tag a new point release?

**Comment by bobmulder** [comment]
Thanks for noticing @dakota, I used the default one of Cake to have some good guidelines ;)
