### ISSUE TITLE
Install failes

### ISSUE THREAD

**Issue by ulistaerk** [cakemanager/cakephp-notifier#16]
Can not install the plugin:
php composer.phar create-project --prefer-dist cakephp/app cakeadmintestapp
cd cakeadmintestapp
php ../composer.phar require cakeplugins/notifier
bin/cake plugin install -b Notifier

fails: Error: Unknown short option `b`

If I use the load plugin it works:
bin/cake plugin load Notifier

But the next step fails:
bin/cake migrations migrate Notifier
Exception: Plugin Notifier could not be found. in [/var/www/vhosts/workspace_us/htdocs/cakeadmintestapp/vendor/cakephp/cakephp/src/Core/Plugin.php, line 148]

**Comment by bobmulder** [comment]
Sounds very strange to me, what version did you install of CakePHP itself?

**Comment by ulistaerk** [comment]
according to composer.json:
        "php": ">=5.5.9",
        "cakephp/cakephp": "~3.2",
        "mobiledetect/mobiledetectlib": "2._",
        "cakephp/migrations": "~1.0",
        "cakephp/plugin-installer": "_",
        "cakeplugins/notifier": "^1.1"

It is: 3.2.12

**Comment by bobmulder** [comment]
Can it be the 3.3.0-beta release or not?

**Comment by bobmulder** [comment]
### Problem 1

> Can not install the plugin:
> php composer.phar create-project --prefer-dist cakephp/app cakeadmintestapp
> cd cakeadmintestapp
> php ../composer.phar require cakeplugins/notifier
> bin/cake plugin install -b Notifier
> 
> fails: Error: Unknown short option b

This can be solved using `load` instead of `install`. My fault, because it's documented this way in the documentation ;) So `cake plugin load -b Notifier` should work.

Problem 2 will follow up ;)

**Comment by bobmulder** [comment]
### Problem 2

> If I use the load plugin it works:
> bin/cake plugin load Notifier
> 
> But the next step fails:
> bin/cake migrations migrate Notifier
> Exception: Plugin Notifier could not be found. in [/var/www/vhosts/workspace_us/htdocs/cakeadmintestapp/vendor/cakephp/cakephp/src/Core/Plugin.php, line 148]

I know whats wrong here. I've moved several times from namespace because of the organisation name. The plugin should be called `CakePlugins/Notifier`, but since the organisation name 'CakePlugins' isn't allowed by the Cake Organisation I've to rename it. 

I will do this today, and will fix all documentation issues so you can use this library. My apologies for all struggles!

**Comment by bobmulder** [comment]
Hi @ulistaerk,

As you see the repository has been moved.

You can install the plugin following the readme: https://github.com/bakkerij/notifier
