### ISSUE TITLE
Package list update

### ISSUE THREAD

**Issue by b1scuit** [cakemanager/cakephp-notifier#19]
Can the packagelist page for the plugin be updated as the old version is still in place so composer is still pulling the older version of this application and causing errors with cakePHP

[https://packagist.org/packages/bakkerij/notifier](https://packagist.org/packages/bakkerij/notifier)

Thanks for any help.

**Comment by bobmulder** [comment]
Sorry for the delay @ChickenBiscuit. 

I don't get what's wrong with packagist? I just abandoned https://packagist.org/packages/cakemanager/cakephp-notifier and suggested https://packagist.org/packages/bakkerij/notifier.

**Comment by lorro** [comment]
If we do `composer require bakkerij/notifier` version 1.2.0 gets pulled in by composer which has a dependendy of cakePHP 3.2.\* So it won't be pulled in when you're running the latest cakePHP namely 3.3.3.

If I do `composer require bakkerij/notifier:dev-master`, all gets pulled in correctly. As that version depends on 3.3.*.

**Comment by bobmulder** [comment]
So we need a 1.2.1 release @lorro?

**Comment by b1scuit** [comment]
Not yet, probably a few more things to do before another version release
I'd say

**Comment by bobmulder** [comment]
Yeah, but to get 1.2 fixed, I'll release 1.2.1 which means it's a simple bugfix (not a 'big' release like 1.3 would be).

**Comment by bobmulder** [comment]
Fixed through https://github.com/bakkerij/notifier/releases/tag/1.2.1
