### ISSUE TITLE
How to render notification to view ?

### ISSUE THREAD

**Issue by iaditya** [cakemanager/cakephp-notifier#9]
Hello, I am new in CakePHP.

Here is my code -

```
// bootstrap.php
  `use Notifier\Utility\NotificationManager;
Plugin::load('Migrations');
Plugin::load('Notifier', ['bootstrap' => true, 'routes' => true, 'autoload' => true]);
$notificationManager = new NotificationManager();
$notificationManager->addTemplate('add', [
    'title' => 'New blog by :username',
    'body' => ':username has posted a new blog named :name'
]);`

// BookmarksController.php
`public function index()
    {
        $this->paginate = [
            'contain' => ['Users', 'Tags']
        ];
        $bookmarks = $this->paginate($this->Bookmarks);
        $this->Notifier->notify([
            'users' => [1],
            'template' => 'add',
            'vars' => [
                'username' => 'Aditya',
                'name' => 'My great new blogpost'
            ],
        ]);
public function add() {....}`
```

I am not seeing any notification.
I don't understand how to use this plugin?
Please describe in details.
Thank You

**Comment by akkaweb** [comment]
What you just did is add a notification into your database. Now it is up to you to pull that into your view. This plugin already provides your with several methods to do that. Here are some examples:

https://github.com/cakemanager/cakephp-notifier#lists

For example I would do this in your controller:

```
public function index(){
    // .... 
    // getting a list of all notifications of the current logged in user
    $this->set('notifications', $this->Notifier->getNotifications());
```

And in your view you can get the notifications by using the `$notifications` variable

```
    // In your view ie. index.ctp
    foreach($notifications as $notification){
        // Then you can make it fit in your view template
        print_r($notification);
   }
```

**Comment by bobmulder** [comment]
Thank you @akkaweb for responding on this issue!

@iaditya were you able to get ik working?

**Comment by iaditya** [comment]
@akkaweb , Please describe the 'template' which are using in both? And what does bootstrap.php code do for notification? Thanks in advance.

**Comment by bobmulder** [comment]
@iaditya you almost answered yourself. Templates are registered in the `bootstrap.php`. Take a look at this: https://github.com/cakemanager/cakephp-notifier#templates

**Comment by iaditya** [comment]
Sorry , still not getting.
I have a controller and under controller an index method. 
//bController.php

```
index() {
$this->Notifier->notify([
            'users' => [1,2],
            'template' => 'new', // what does mean ??
            'vars' => [
                'username' => 'Aditya',
                'name' => 'My great new blogpost'
            ],
        ])
}
```

bootstrap.php : what does new describe here?

```
$notificationManager->addTemplate('new', [
    'title' => 'New blog by :username',
    'body' => ':username has posted a new blog named :name'
]);
```

**Comment by bobmulder** [comment]
Okay, I'll try to explain again.

This plugin works wih a template strategy. That means that a notification uses a template to 'build' its sentence. So, when you are calling the `notify` method to create a new notification, only the variables (`vars`) are saved in your database. When the notification should be shown, the chosen template should be used to 'build' its sentences with the stored variables.

So according to your example, you choose to use the `new` template (which is registered in your `bootstrap.php`. The method will store the variables `username` and `name`.
When you'll display the notification, it will get the template and show you the title like `New blog by Aditya` and the body like `Aditya has posted a new blog named My great new blogpost`.

Hope you'll get it now. Probably I should clear the docs? ;)

Good luck!

**Comment by iaditya** [comment]
thanks , I understood.
It's saving the data in Table. But in -
/bCtrl
`index() { $this->Notifier->notify(.....); $notifications = $this->Notifier->getNotifications();  $this->set(compact('notifications')); }`
/index.ctp
`<?php dump($notifications); ?>`

print null array.

**Comment by bobmulder** [comment]
Sure you logged in with user with id `1` or `2`?

**Comment by iaditya** [comment]
It's working .
Thank you once again for giving your time.

**Comment by bobmulder** [comment]
Thanks for @akkaweb as well!
